codepaces reference
4GeeksAcademy/python-functions-programming-exercises pull request #45
Opened 2023-04-13 19:49 UTC by Lorenagubaira

2023-04-19 21:13 UTC, tommygonzaleza requested changes

2023-04-19 21:13 UTC, tommygonzaleza commented on README.es.md
> +Puedes empezar estos ejercicios en pocos segundos haciendo clic en: [Abrir en Codespaces](https://codespaces.new/?repo=4GeeksAcademy/css-layouts-tutorial-exercises) (recomendado) o [Abrir en Gitpod](
El link del repositorio tiene el de css

2023-04-27 21:42 UTC, tommygonzaleza approved these changes

2023-05-01 13:52 UTC, alesanchezr approved these changes

2023-05-01 13:52 UTC, merged